version: "3"
services:
  rocketchat:
    build: .
    environment:
    - PORT=8006
    - MONGO_DATABASE=rocketchat
    - MONGO_HOST=mongo:27018
    - MONGO_OPLOG_HOST=mongo:27018
    - ROOT_URL=http://127.0.0.1:8006
    links:
    - mongo
  mongo:
    image: mongo:3.2-jessie
    volumes:
    - /srv/mongo:/data/db
    ports:
    - "27018:27017"
    command: mongod --oplogSize 128 --replSet rs0
